name: Build and Upload JAR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build JAR
      run: mvn -B package
      working-directory: TicTacToeProject

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: TicTacToeGame
        path: TicTacToeProject/target/*.jar
